name: Scrape Podcasts

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  Scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn podcast:scrape
